# 这是IceinuBot的配置文件，由程序在初次运行时自动生成
# 仓库地址：https://github.com/KyokuKong/go-iceinu
# 出现修改了配置文件结构的大版本更新时应备份后重新生成该配置文件
# 你可以在仓库的README.md中找到配置文件模板
# ----------------------------------------------------

[onebot] # 与Onebot客户端进行连接时所需的配置
# ----------------------------------------------------
# 配置对onebot的反向ws连接，传入的URL字符串格式为"ws://onebot客户端IP:端口"
# 可以传入多个URL来实现多Bot连接，每个连接都会被IceinuBot注册成一个Driver
websocket_connects = ["ws://127.0.0.1:23333"]
# 配置与onebot客户端进行通信时使用的反向token，推荐使用一个随机的16-64位十六进制字符串
# 留空可以不设置，但是这样可能导致一些难以预料的安全问题
# 同时连接多个Onebot客户端时需要将每个客户端的token都设置成相同的
access_token = ""

[database] # 数据库连接设置
# ----------------------------------------------------
# 配置数据库远程连接的URL
# Iceinu的数据库连接及处理都通过gorm进行，理论上gorm兼容的SQL数据库都可以使用
# 但是保证可用性的数据库只有PostgreSQL、MySQL以及内置的SQLite
sql_connect = "sqlite:///iceinu.db"
# 连接池上限，设置更多的连接池可以同时向数据库发出更多查询请求，但是会影响性能表现
# 一般不需要设置的太高
db_conn_pool = 10

[bot] # IceinuBot自身的设置
# ----------------------------------------------------
# 设置Bot展示的自身名称
nickname = "IceInuBot"
# 设置命令前缀
command_prefix = "/"
# 设置超级管理员用户，拥有Bot的所有权限，包括设置其他管理员
# Bot会将部分使用日志和消息自动发送到这个账号上
superuser = [1234567890]
# 启用自动更新，会在每天凌晨4点自动从Github上检查是否有新的Release版本并尝试下载
# 如果下载成功那么会尝试自行覆盖并重启Bot
auto_update = false
# Bot向命令行输出日志的等级阈值，一般使用INFO即可
# 当Bot使用量非常巨大以至于输出到命令行的日志会一定程度上影响性能时，可以尝试将其设置到更高的等级
# 但是日志事实上对性能的影响微乎其微，出现这种情况更多可能说明设备需要换新了
log_level = "INFO"
# 是否启用远程管理api，关闭远程管理api后将无法使用iceinu manager
# 远程管理api的默认鉴权用户名为admin，密码为iceinubot，请在启动后立刻修改
# 远程管理api中的每一个账户的权限都和superuser相同，请谨慎将远程管理api的用户给予他人
enable_remote_api = true
