# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release

on:
  push:
    tags:
      - "v0.*"
      - "draft-*"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.5"

      - name: Install dependencies
        working-directory: ./bot
        run: go mod tidy

      - name: Build for Linux x64
        working-directory: ./bot
        run: GOOS=linux GOARCH=amd64 go build -o build/go-iceinu-linux-amd64-${{ github.ref_name }} .

      - name: Build for Windows x64
        working-directory: ./bot
        run: GOOS=windows GOARCH=amd64 go build -o build/go-iceinu-windows-amd64-${{ github.ref_name }}.exe .

      - name: Upload Linux binary
        uses: actions/upload-artifact@v3
        with:
          name: go-iceinu-linux-amd64-${{ github.ref_name }}
          path: ./bot/build/go-iceinu-linux-amd64-${{ github.ref_name }}

      - name: Upload Windows binary
        uses: actions/upload-artifact@v3
        with:
          name: go-iceinu-windows-amd64-${{ github.ref_name }}
          path: ./bot/build/go-iceinu-windows-amd64-${{ github.ref_name }}.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files:  ./bot/build/*
          draft: true
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
