# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release

on:
  push:
    tags:
      - "v0.*"
      - "draft-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.5"

      - name: Install dependencies
        working-directory: ./bot
        run: go mod tidy

      - name: Build for Windows x86
        working-directory: ./bot
        run: GOOS=windows GOARCH=386 go build -o build/go-iceinu-windows-x86-${{ github.ref_name }}.exe .

      - name: Build for Windows amd64
        working-directory: ./bot
        run: GOOS=windows GOARCH=amd64 go build -o build/go-iceinu-windows-amd64-${{ github.ref_name }}.exe .

      - name: Build for Windows arm64
        working-directory: ./bot
        run: GOOS=windows GOARCH=arm64 go build -o build/go-iceinu-windows-arm64-${{ github.ref_name }}.exe .

      - name: Build for Linux x86
        working-directory: ./bot
        run: GOOS=linux GOARCH=386 go build -o build/go-iceinu-linux-x86-${{ github.ref_name }} .

      - name: Build for Linux amd64
        working-directory: ./bot
        run: GOOS=linux GOARCH=amd64 go build -o build/go-iceinu-linux-amd64-${{ github.ref_name }} .

      - name: Build for Linux arm64
        working-directory: ./bot
        run: GOOS=linux GOARCH=arm64 go build -o build/go-iceinu-linux-arm64-${{ github.ref_name }} .

      - name: Build for OSX amd64
        working-directory: ./bot
        run: GOOS=darwin GOARCH=amd64 go build -o build/go-iceinu-osx-amd64-${{ github.ref_name }} .

      - name: Build for OSX arm64
        working-directory: ./bot
        run: GOOS=darwin GOARCH=arm64 go build -o build/go-iceinu-osx-arm64-${{ github.ref_name }} .

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./bot/build/*

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bot/build/*
          body: GithubCI自动构建的Release版本，更新内容详见仓库README.md中的更新记录
          draft: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
